
package dylangomezvazquez.acculaden;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ApplicatieFout", targetNamespace = "http://dylangomezvazquez/AccuLadenError")
public class ApplicatieFout
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private dylangomezvazquez.acculadenerror.ApplicatieFout faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ApplicatieFout(String message, dylangomezvazquez.acculadenerror.ApplicatieFout faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ApplicatieFout(String message, dylangomezvazquez.acculadenerror.ApplicatieFout faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: dylangomezvazquez.acculadenerror.ApplicatieFout
     */
    public dylangomezvazquez.acculadenerror.ApplicatieFout getFaultInfo() {
        return faultInfo;
    }

}
