
package dylangomezvazquez.acculaden;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import dylangomezvazquez.acculadenrequest.AccuLadenRequest;
import dylangomezvazquez.acculadenresponse.AccuLadenResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WS-Interface", targetNamespace = "http://dylangomezvazquez/AccuLaden")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    dylangomezvazquez.acculadenerror.ObjectFactory.class,
    dylangomezvazquez.acculadenrequest.ObjectFactory.class,
    dylangomezvazquez.acculadenresponse.ObjectFactory.class
})
public interface WSInterface {


    /**
     * 
     * @param request
     * @return
     *     returns dylangomezvazquez.acculadenresponse.AccuLadenResponse
     * @throws ApplicatieFout
     */
    @WebMethod(operationName = "AccuLaden")
    @WebResult(name = "AccuLadenResponse", targetNamespace = "http://dylangomezvazquez/AccuLadenResponse", partName = "response")
    public AccuLadenResponse accuLaden(
        @WebParam(name = "AccuLadenRequest", targetNamespace = "http://dylangomezvazquez/AccuLadenRequest", partName = "request")
        AccuLadenRequest request)
        throws ApplicatieFout
    ;

}
